"""initial migration

Revision ID: 11da4ac4be09
Revises: None
Create Date: 2015-08-26 11:24:49.828968

"""

# revision identifiers, used by Alembic.
revision = '11da4ac4be09'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
