"""empty message

Revision ID: 26b1bc53a88b
Revises: 4643907d5be4
Create Date: 2015-08-28 00:41:24.864322

"""

# revision identifiers, used by Alembic.
revision = '26b1bc53a88b'
down_revision = '4643907d5be4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_preview')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_preview', sa.TEXT(), nullable=True))
    ### end Alembic commands ###
