"""empty message

Revision ID: 4643907d5be4
Revises: 53e0ab96a4ed
Create Date: 2015-08-27 15:58:23.668957

"""

# revision identifiers, used by Alembic.
revision = '4643907d5be4'
down_revision = '53e0ab96a4ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_preview', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_preview')
    ### end Alembic commands ###
